dependencies:
- name: redis
  version: "^1.2.2"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
- name: postgresql
  version: "^0.9.5"
  repository: "https://kubernetes-charts.storage.googleapis.com/"