apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redash.fullname" . }}
  labels:
    app: {{ template "redash.name" . }}
    chart: {{ template "redash.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  createdb.sh: |
    #!/usr/bin/env bash
    # Check PostgreSQL is up and create the database on first run.
    . /config/dynamicenv.sh
    echo "Checking status."
    while /app/manage.py status 2>&1 | grep 'sqlalchemy.exc.OperationalError'; do
      echo "Database not yet functional, waiting."
      sleep 10
    done
    sleep 5
    if /app/manage.py status 2>&1 | grep 'sqlalchemy.exc.ProgrammingError'; then
      echo "Database tables not ready, creating tables now."
      /app/manage.py database create_tables
    fi
  dynamicenv.sh: |
    # Build connection URLs from environment variables.
    # NOTES:
    #   This script should be sourced, not run directly.
    #   All variables are expected to be set by the caller.
    export REDASH_DATABASE_URL=postgresql://${REDASH_DATABASE_USER}:${REDASH_DATABASE_PASSWORD}@${REDASH_DATABASE_HOSTNAME}:${REDASH_DATABASE_PORT}/${REDASH_DATABASE_DB}
    echo "Using Database: postgresql://${REDASH_DATABASE_USER}:******@${REDASH_DATABASE_HOSTNAME}:${REDASH_DATABASE_PORT}/${REDASH_DATABASE_DB}"
    export REDASH_REDIS_URL=redis://:${REDASH_REDIS_PASSWORD}@${REDASH_REDIS_HOSTNAME}:${REDASH_REDIS_PORT}/${REDASH_REDIS_DB}
    echo "Using Redis: redis://:******@${REDASH_REDIS_HOSTNAME}:${REDASH_REDIS_PORT}/${REDASH_REDIS_DB}"