apiVersion: v1
kind: Service
metadata:
  name: {{ template "redash.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "redash.name" . }}
    helm.sh/chart: {{ template "redash.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.server.httpPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ template "redash.name" . }}
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}