apiVersion: v1
kind: Service
metadata:
  name: {{ template "redash.fullname" . }}
  labels:
    app: {{ template "redash.name" . }}
    chart: {{ template "redash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.server.httpPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "redash.name" . }}
    component: "{{ .Values.server.name }}"
    release: {{ .Release.Name }}